/**
 * @file Automatically generated by barrelsby.
 */

export * from "./auth/auth.controller";
export * from "./collectable/collectable.controller";
export * from "./role/role.controller";
export * from "./scene/scene.controller";
export * from "./user/user.controller";
export * from "./userSceneProgress/userSceneProgress.controller";
export * from "./avatar/avatar.controller";
